services:
  server:
    image: minimail
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CONN_STRING: dbname=postgres user=postgres password=postgres host=postgres port=5432
    ports:
      - "8080:8080"

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: null
