services:
  server:
    image: minimail-server
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CONN_STRING: dbname=postgres user=postgres password=postgres host=postgres port=5432
    ports:
      - "8080:8080"

  client-spa:
    image: minimail-client-spa
    build:
      context: ./static/spa
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: null
